### ISSUE TITLE
Clicking [Add to Favorites] button forced refresh

### ISSUE THREAD

**Issue by yuni114** [YURAresearch/YURAResearchDatabase#28]
After clicking [Add to Favorites] the web-page is forced to refresh. This resets the search and brings the user back to the main homepage with all faculty listed, making the [Add to Favorites] function somewhat troublesome to use (the user has to re-type in the searches each time they add a faculty to favorites). Is there any way to code the [Add to Favorites] so that the page does not refresh upon clicking?

**Comment by yuni114** [comment]
Also seem to be having trouble adding labels to Issues (maybe cuz we have restricted access?)

**Comment by suryadutta** [comment]
Great Idea! I was actually looking at how to do this. With the current framework, I don't think I can prevent the page from refreshing, but I think i can make it so the search doesn't go away and you're redirected to the subset of faculty you were originally looking at

**Comment by suryadutta** [comment]
Added this functionality, but exposed problem with sort. Will open another issue.
