### ISSUE TITLE
Separate Filter and Sort into two forms

### ISSUE THREAD

**Issue by suryadutta** [YURAresearch/YURAResearchDatabase#29]
Right now, since the get form on the listings pages submits all values, it is automatically placing the "sort" functionality in the query. This removes ranking by favorites or other algorithms. We need to separate this into two forms, while making sure no search feature is lost.

Frontend task: splitting the form into two forms with proper formatting

Backend task: make sure that these two forms save each other's progress

**Comment by wyppeter** [comment]
Sort buttons don't add much to the functionality and usefulness of the tool, and occupies more space than it's worth. Was planning of getting rid of sort anyway, so just get rid of the sorting part of query.
