### ISSUE TITLE
Fix fonts on the info homepage of RDB

### ISSUE THREAD

**Issue by wyppeter** [YURAresearch/YURAResearchDatabase#8]

**Comment by wyppeter** [comment]
Including the misplaced/sized blue triangles of the FAQs

**Comment by mwufi** [comment]
Could you say more about this? What should we fix?

**Comment by wyppeter** [comment]
Fonts are too small and there is excess whitespace, possibly due to font-size definition conflicts and mistakes (%s). 
The blue triangles in the FAQs boxes should be aligned with the upper left corner of the white boxes
